config/routes.rb
Rails.application.routes.draw do
  root "entries#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "auth/:provider/callback", to: "sessions#create"

  get "login", to: redirect("/auth/openid_connect"), as: "login" if Rails.env == "production"
  get "login", to: redirect("/auth/developer"), as: "login" unless Rails.env == "production"


  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  resources :entries
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user

  attribute :message, :string
  attribute :due, :date
  attribute :priority, :integer
end

app/models/user.rb
class User < ApplicationRecord
  has_many :entries

  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }, presence: true, uniqueness: true

  def self.from_omniauth(access_token)
    data = access_token.info
    email = data["email"]

    User.find_or_create_by(email:)
  end
end

app/controllers/application_controller.rb
require "omniauth"

class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  protect_from_forgery with: :exception
  helper_method :current_user

  def require_authentication
    redirect_to login_path, method: :post, alert: "Requires authentication" unless user_signed_in?
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def user_signed_in?
    # converts current_user to a boolean by negating the negation
    !!current_user
  end

  def new
    # code here
  end

  def index
    # code here
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :require_authentication

  def index
    @entries = Entry.all
    print @current_user
  end

  def show
    @entry = Entry.find(params[:id])
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :require_authentication

  def index
    @entries = @current_user.entries
  end

  def show
    @entry = Entry.find(params[:id])
  end

  def new
    @entry = Entry.new
  end

  def edit
    @entry = Entry.find(params[:id])
  end

  def create
    @entry = Entry.new(entry_params)
    @entry.user = @current_user

    if @entry.save
      redirect_to entries_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @entry = Entry.find(params[:id])

    if @entry.update(entry_params)
      redirect_to entries_path, flash: { notice: "Updated entry \"#{@entry.message}\"" }
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @entry = Entry.find(params[:id])
    flash[:notice] = "Deleted entry \"#{@entry.message}\""
    @entry.destroy

    redirect_to entries_path, status: :see_other
  end

  private
  def entry_params
    params.require(:entry).permit(:message, :due, :priority)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    print request.env["omniauth.auth"]
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      session[:user_id] = @user.id
      redirect_to entries_path, notice: "Logged in as #{@user.email}"
    else
      redirect_to root_url, alert: "Failure"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/edit.html.erb
<h1>Edit Todo Entry "<%= @entry.message %>"</h1>

<%= form_with model: @entry do |form| %>
  <div>
    <%= form.label :message %><br>
    <%= form.text_area :message %>
  </div>

  <div>
    <%= form.label :due %><br>
    <%= form.date_field :due %>
  </div>

  <div>
    <%= form.label :priority, "Priority (1-10)" %><br>
    <%= form.number_field :priority, max: 10, min: 1 %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/entries/index.html.erb
<h2>Notes:</h2>
<div>
  <% @entries.each do |entry| %>
      <div class="card" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title">Note #<%= entry.id %></h5>
          <p class="card-text"><%= entry.message %></p>
          <p class="card-text">Due <%= entry.due %></p>
          <%= link_to "View",
                      entry_path(entry),
                      :class => "btn btn-primary" %>
          <%= link_to "Edit",
                      edit_entry_path(entry),
                      :class => "btn btn-primary" %>
          <%= link_to "Delete",
                      entry,
                      :class => "btn btn-primary",
                      data: {
                        turbo: true,
                        turbo_method: :delete,
                        turbo_confirm: "Are you sure you want to delete this note?"
                      } %>
        </div>
      </div>
  <% end %>
</div>

app/views/entries/new.html.erb
<h1>New Todo Entry</h1>

<%= form_with model: @entry do |form| %>
  <div>
    <%= form.label :message %><br>
    <%= form.text_area :message %>
  </div>

  <div>
    <%= form.label :due %><br>
    <%= form.date_field :due %>
  </div>

  <div>
    <%= form.label :priority, "Priority (1-10)" %><br>
    <%= form.number_field :priority, max: 10, min: 1 %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/entries/show.html.erb
<h1>Note <%= @entry.id %></h1>
<div>
    <p>
      <%= @entry.message %>
    </p>
    <p>
      Due: <%= @entry.due %>
      Priority: <%= @entry.priority %>
    </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= content_for(:title) || "Todo Manager" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload", media: "all" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <%= turbo_include_tags %>
  </head>

  <body class="w-100 flex-column">
    <% if flash[:alert] %>
      <div class="notice w-100 bg-danger text-bg-danger text-center p-1"><%= flash[:alert] %></div>
    <% end %>
    <% if flash[:notice] %>
      <div class="notice w-100 bg-info text-center p-1"><%= flash[:notice] %></div>
    <% end %>
    <div class="row w-100">
      <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-light" style="max-width: 200px">
        <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
          <a href="/" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
            <span class="fs-5 d-none d-sm-inline">Menu</span>
          </a>
          <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
            <li class="nav-item">
              <%= link_to root_path, class: "nav-link align-middle px-0" do %>
                <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline">Home</span>
              <% end %>
            </li>
            <li>
              <a href="#submenu1" data-bs-toggle="collapse" class="nav-link px-0 align-middle">
                <i class="fs-4 bi-sticky"></i> <span class="ms-1 d-none d-sm-inline">Todo Manager</span> </a>
              <ul class="collapse show nav flex-column ms-1" id="submenu1" data-bs-parent="#menu">
                <li class="w-100 fs-6">
                  <%= link_to entries_path, :class => "nav-link px-0" do %>
                    <i class="bi-stickies"> </i><span class="d-none d-sm-inline">View All</span>
                  <% end %>
                </li>
                <li class="w-100 fs-6">
                  <%= link_to new_entry_path, :class => "nav-link px-0" do %>
                    <i class="bi-plus-square"> </i> <span class="d-none d-sm-inline">Create New</span>
                  <% end %>
                </li>
              </ul>
            </li>
          </ul>
          <hr>
        </div>
      </div>
      <section class="col-sm p-3 min-vh-100">
        <h1>Todo Notes Application</h1>
        <hr />
        <%= yield %>
      </section>
    </div>
  </body>
</html>